name: run-tests
run-name: Installs project and runs tests
on: [push, pull_request]
jobs:
    run-tests-nix:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [20]
        name: Run tests on Ubuntu with Node ${{ matrix.node }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: |
                  if [[ -d node_module/@typescript-eslint ]]; then
                      echo "@typescript-eslint package exists in root directory."
                  else 
                      echo "@typescript-eslint package does not exist in root directory."
                  fi

                  if [[ -d node_module/@graphql-eslint ]]; then
                      echo "@graphql-eslint package exists in root directory."
                  else 
                      echo "@graphql-eslint package does not exist in root directory."
                  fi

            - run: npm run test
    run-tests-win:
        runs-on: windows-latest
        strategy:
            matrix:
                node: [20]
        name: Run tests on Windows with Node ${{ matrix.node }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm run test
